azs:
- name: z1
  cloud_properties:
    zone: ((z1))
- name: z2
  cloud_properties:
    zone: ((z2))
- name: z3
  cloud_properties:
    zone: ((z3))

vm_types:
- name: t2.small
  cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 15
    root_disk_type: pd-standard
- name: m3.medium
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 50
    root_disk_type: pd-standard
- name: m3.large
  cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 50
    root_disk_type: pd-standard
- name: r3.xlarge
  cloud_properties:
    machine_type: n1-highmem-4
    root_disk_size_gb: 50
    root_disk_type: pd-standard
- name: c3.large
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 15
    root_disk_type: pd-standard

disk_types:
- name: 1GB
  disk_size: 1024
  cloud_properties:
    type: pd-standard
    encrypted: true
- name: 5GB
  disk_size: 5120
  cloud_properties:
    type: pd-standard
    encrypted: true
- name: 10GB
  disk_size: 10240
  cloud_properties:
    type: pd-standard
    encrypted: true
- name: 50GB
  disk_size: 51200
  cloud_properties:
    type: pd-standard
    encrypted: true
- name: 100GB
  disk_size: 102400
  cloud_properties:
    type: pd-standard
    encrypted: true
- name: 500GB
  disk_size: 512000
  cloud_properties:
    type: pd-standard
    encrypted: true
- name: 1TB
  disk_size: 1048576
  cloud_properties:
    type: pd-standard
    encrypted: true

compilation:
  workers: 6
  network: private
  az: z1
  reuse_compilation_vms: true
  vm_type: c3.large
  vm_extensions:
  - 100GB_ephemeral_disk

networks:
- name: private
  type: manual
  subnets:
  - azs:
    - z1
    - z2
    - z3
    gateway: ((internal_gw))
    dns:
    - ((internal_gw))
    range: ((internal_cidr))
    reserved: ((reserved_ips))
    static:
    - ((static_ip_start)) - ((static_ip_end))
    cloud_properties:
      ephemeral_external_ip: false
      network_name: ((network))
      subnetwork_name: ((subnetwork))
      tags: ((internal_tags))

vm_extensions:
- name: 5GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 5120
      type: pd-standard
- name: 10GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 10240
      type: pd-standard
- name: 50GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 51200
      type: pd-standard
- name: 100GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 102400
      type: pd-standard
- name: 500GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 512000
      type: pd-standard
- name: 1TB_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 1048576
      type: pd-standard

- name: cf-internet-required
  cloud_properties:
    ephemeral_external_ip: true
- name: cf-internet-not-required
  cloud_properties:
    ephemeral_external_ip: false

- name: cf-router-network-properties
  cloud_properties:
    backend_service: ((http_backend_service))
    target_pool: ((ws_target_pool))
    tags: ((public_tags))

- name: cf-tcp-router-network-properties
  cloud_properties:
    target_pool: ((tcp_target_pool))
    tags: ((tcp_tags))

- name: diego-ssh-proxy-network-properties
  cloud_properties:
    target_pool: ((ssh_target_pool))
    tags: ((ssh_tags))
